version: "2"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    ports:
      - "9200:9200"
    volumes:
      - ~/.scripts/elasticsearch/esdata/:/usr/share/elasticsearch/data/

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
